### ISSUE TITLE
No requirement file in pip version

### ISSUE THREAD

**Issue by azlux** [andreztz/pyradios#1]
Hi,
With pip command install, I have this error.
```
Collecting pyradios
  Using cached https://files.pythonhosted.org/packages/7b/96/b9de1186df9cc131967e151db72d20a3ff5ab998b3283fb130146ea8c778/pyradios-0.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-np5z4gx1/pyradios/setup.py", line 27, in <module>
        install_requires=required(),
      File "/tmp/pip-build-np5z4gx1/pyradios/setup.py", line 11, in required
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-np5z4gx1/pyradios/
```

On the pypi.org website, the package don't contain the requirement.txt

Az

**Comment by andreztz** [comment]
Issue fixed in version 0.0.13.
