### ISSUE TITLE
Invalid Syntax on import

### ISSUE THREAD

**Issue by hanneseilers** [andreztz/pyradios#28]
Just installed using pip and used on Ubuntu 20.10 and Python 2.7.18

```
import pyradios
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hannes/.local/lib/python2.7/site-packages/pyradios/__init__.py", line 1, in <module>
    from pyradios.radios import RadioBrowser
  File "/home/hannes/.local/lib/python2.7/site-packages/pyradios/radios.py", line 3, in <module>
    from pyradios.base_url import pick_base_url
  File "/home/hannes/.local/lib/python2.7/site-packages/pyradios/base_url.py", line 7, in <module>
    from pyradios.log import logger
  File "/home/hannes/.local/lib/python2.7/site-packages/pyradios/log.py", line 3, in <module>
    from pyradios.utils import setup_log_file
  File "/home/hannes/.local/lib/python2.7/site-packages/pyradios/utils.py", line 81
    first, *others = s.split("_")
```

**Comment by andreztz** [comment]
Sorry Python2.7 is not supported, currently pyradios supports python >= 3.6.
